<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @version 1.0.0 */
/** @var Escaper $escaper */
/** @var Template $block */
$value = $block->getValue();
if (empty($value)) {
    return;
}

$color = class_exists($value) ? '' : '#ffdad6';
?>
<code style="background-color: <?= $escaper->escapeHtml($color) ?>"><?php echo $escaper->escapeHtml($value) ?></code>
